# vim:fileencoding=utf-8:foldmethod=marker

#: Fonts {{{

font_family      Maple Mono NF CN
bold_font        Maple Mono NF CN Bold
italic_font      Maple Mono NF CN Italic
bold_italic_font Maple Mono NF CN Bold Italic

font_size 11.5
modify_font cell_width 95%

#: }}}

#: Cursor customization {{{

cursor_shape block
cursor_blink_interval 0
cursor_stop_blinking_after 0
shell_integration no-cursor

#: }}}

#: Window layout {{{

background_opacity 0.85

#: }}}

#: Color scheme {{{

# Tokyo Night Storm theme
include tokyonight_storm.conf

#: }}}

#: Advanced {{{

# Environment variables
# env TERM=xterm-256color

#: }}}

#: Keyboard shortcuts {{{

# Word navigation (matching alacritty Alt+Left/Right)
# map alt+left send_text all \x1bb
# map alt+right send_text all \x1bf

#: }}}


# BEGIN_KITTY_THEME
# Tokyo Night Storm
include current-theme.conf
# END_KITTY_THEME
