# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

format = '''[$all](bold green)[❯ $git_status](bold green)'''

[character]
success_symbol = ''
error_symbol = ''

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[git_branch]
symbol = ' '
format = '[$symbol$branch(:$remote_branch)]($style) '
truncation_length = 15
truncation_symbol = '…'
ignore_branches = ['master', 'main']

[git_status]
conflicted = ''
modified = '[ ](bold yellow)'
renamed = '[ ](bold blue)'
deleted = '[ ](bold red)'
untracked = '[ ](bold fg:214)'
up_to_date = '✔✘'
format = '([$modified$renamed$deleted$untracked]($style))'

[java]
symbol = ' '

[gcloud]
symbol = '󱇱 '

[gradle]
symbol = ' '

[kotlin]
symbol = '󱈙 '

[rust]
symbol = '󱘗 '

[golang]
symbol = ' '

[nodejs]
symbol = '󰎙 '

[lua]
symbol = ' '
