#!name=claude
#!homepage=https://github.com/sshelll/dotconfigs/shadowrocket
#!desc=Created:09-21 17:02 Publisher:sshelll

[Rule]
DOMAIN-SUFFIX,anthropic.com,PROXY
DOMAIN-SUFFIX,claude.ai,PROXY
DOMAIN-SUFFIX,claude.com,PROXY
DOMAIN-SUFFIX,clau.de,PROXY
DOMAIN-SUFFIX,claudemcpclient.com,PROXY
DOMAIN-SUFFIX,claudemcpcontent.com,PROXY
DOMAIN-SUFFIX,claudeusercontent.com,PROXY
DOMAIN,servd-anthropic-website.b-cdn.net,PROXY
DOMAIN,anthropic.com.cdn.cloudflare.net,PROXY
DOMAIN,anthropic.auth0.com,PROXY
DOMAIN,anthropic-com.ghost.io,PROXY
DOMAIN-SUFFIX,sentry.io,PROXY
DOMAIN-SUFFIX,statsigapi.net,PROXY
DOMAIN,browser-intake-us5-datadoghq.com,PROXY
DOMAIN-KEYWORD,datadog,PROXY
DOMAIN-KEYWORD,sift,PROXY
DOMAIN-SUFFIX,intercom.io,PROXY
DOMAIN-SUFFIX,intercomcdn.com,PROXY
DOMAIN,cdn.usefathom.com,PROXY
IP-CIDR,160.79.104.0/21,PROXY,no-resolve
IP-CIDR6,2607:6bc0::/32,PROXY,no-resolve
