#!name=siri
#!homepage=https://github.com/sshelll/dotconfigs/shadowrocket
#!desc=Created:09-21 11:43 Publisher:sshelll

[Rule]
DOMAIN-SUFFIX,ls.apple.com,PROXY
DOMAIN-SUFFIX,mask-api.icloud.com,PROXY
DOMAIN-SUFFIX,mask-h2.icloud.com,PROXY
DOMAIN-SUFFIX,mask.icloud.com,PROXY
DOMAIN-KEYWORD,gspel-ssl,PROXY
DOMAIN-SUFFIX,smoot.apple.com,PROXY
DOMAIN-SUFFIX,gspe1-ssl.ls.apple.com,PROXY
DOMAIN-SUFFIX,guzzoni.apple.com,PROXY
DOMAIN-SUFFIX,gateway.icloud.com,PROXY
DOMAIN-KEYWORD,apple-relay,PROXY
