#!name=siri
#!homepage=https://github.com/sshelll/dotconfigs/shadowrocket
#!desc=Created:09-21 11:50 Publisher:sshelll

[Proxy Group]
Siri = select,🇨🇳 台湾 02,use=true

[Rule]
DOMAIN-SUFFIX,ls.apple.com,Siri
DOMAIN-SUFFIX,mask-api.icloud.com,Siri
DOMAIN-SUFFIX,mask-h2.icloud.com,Siri
DOMAIN-SUFFIX,mask.icloud.com,Siri
DOMAIN-KEYWORD,gspel-ssl,Siri
DOMAIN-SUFFIX,smoot.apple.com,Siri
DOMAIN-SUFFIX,gspe1-ssl.ls.apple.com,Siri
DOMAIN-SUFFIX,guzzoni.apple.com,Siri
DOMAIN-SUFFIX,gateway.icloud.com,Siri
DOMAIN-KEYWORD,apple-relay,Siri
DOMAIN-SUFFIX,apple.com,Siri
DOMAIN-SUFFIX,cdn-apple.com,Siri
